version: "3.7"
services:
  app:
    image: valentinriess/photoprism-album-sync:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./cache:/app/cache # This is the place where the pictures will be downloaded to
      - ./data:/app/data # Mount photoprism album yaml file here
    env_file: .env
    environment:
      - SYNC_BASE_URL=${SYNC_BASE_URL}
      - PHOTOPRISM_SYNC_ALBUM_PATH=${PHOTOPRISM_SYNC_ALBUM_PATH}
      - SYNC_CACHE_PATH=${SYNC_CACHE_PATH}
      - SYNC_USERNAME=${SYNC_USERNAME}
      - SYNC_PASSWORD=${SYNC_PASSWORD}
      - SYNC_TYPE=${SYNC_TYPE}